name: Daily Data Fetch

on:
  schedule:
    - cron: '0 8 * * *' # Runs every day at 8:00 AM UTC
  workflow_dispatch:    # Allows you to click a button to run it manually

permissions:
  contents: write       # Gives the robot permission to save the file

jobs:
  refresh-feed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run the Robot
        run: node fetch-data.js

      - name: Save changes
        run: |
          git config user.name "Bot"
          git config user.email "bot@users.noreply.github.com"
          git add polls.json
          git commit -m "Update poll data" || exit 0
          git push